Repository languagetool-org/portuguese-pos-dict, pull requests merged in 2024-05, with the labels that each got.

#36 [pt-PT] Added words to both dictionaries (.dic)
  data/spelling-dict/hunspell/pt_BR.dic
  data/spelling-dict/hunspell/pt_PT_45.dic
  data/spelling-dict/hunspell/pt_PT_90.dic
  data/src-dict/adv_mente-lt.txt
  data/src-dict/nouns-fdic.txt
  data/src-dict/propernouns-lt.txt
Labels: enhancement

#40 Add new words from last 60 days
  data/spelling-dict/hunspell/pt_BR.dic
  data/spelling-dict/hunspell/pt_PT_45.dic
  data/spelling-dict/hunspell/pt_PT_90.dic
  data/src-dict/interjections-lt.txt
  data/src-dict/nouns-fdic.txt
  data/src-dict/propernouns-lt.txt
  data/src-dict/verbs-fdic.txt
Labels: missing_word

#42 Fix lemma of dim/augm determiners
  data/src-dict/resta-lt.txt
Labels: morph
