Repository languagetool-org/portuguese-pos-dict, pull requests merged in 2024-04, with the labels that each got.

#32 [pt] Added postags to numerals-lt.txt
  data/src-dict/numerals-lt.txt
Labels: morph

#33 Accept 'email' alongside 'e-mail'
  data/spelling-dict/hunspell/compounds/pt_PT_45.dic
  data/spelling-dict/hunspell/compounds/pt_PT_90.dic
  data/spelling-dict/hunspell/pt_BR.dic
  data/spelling-dict/hunspell/pt_PT_45.dic
  data/spelling-dict/hunspell/pt_PT_90.dic
Labels: missing_word, tricky

#34 Add random words from issues
  data/spelling-dict/hunspell/pt_BR.dic
  data/spelling-dict/hunspell/pt_PT_45.dic
  data/spelling-dict/hunspell/pt_PT_90.dic
  data/src-dict/nouns-fdic.txt
  data/src-dict/propernouns-lt.txt
Labels: missing_word

#35 Add original 150 pokemon
  data/spelling-dict/hunspell/pt_BR.aff
  data/spelling-dict/hunspell/pt_BR.dic
  data/spelling-dict/hunspell/pt_PT_45.aff
  data/spelling-dict/hunspell/pt_PT_45.dic
  data/spelling-dict/hunspell/pt_PT_90.aff
  data/spelling-dict/hunspell/pt_PT_90.dic
  data/src-dict/propernouns-lt.txt
Labels: missing_word
